apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-auth
  namespace: semantic-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-auth
  template:
    metadata:
      labels:
        app: request-auth
    spec:
      containers:
        - name: request-auth
          image: request-auth-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: AUTH_APIKEY
              value: "dev-api-key"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: request-auth-service
  namespace: semantic-cache
spec:
  selector:
    app: request-auth
  ports:
    - port: 8081
      targetPort: 8081
