apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-semantic-cache-sa
  namespace: eks-semantic-cache
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/eks-semantic-cache-role